### ISSUE TITLE
skin-tone-# vs. _tone#

### ISSUE THREAD

**Issue by marti4ka** [Kikobeats/emojis-keywords#10]
Hi,
thanks for the full list of emojis! 
I am having trouble with the skin tones. When I use slack my emojis look like this: `:santa::skin-tone-3:` -> two emojis for one thing. However, in this list the same emoji looks like this: `:santa_tone3:` -> [here](https://github.com/Kikobeats/emojis-keywords/blob/master/index.js#L451)

What do you think is better? Adding the `skin-tone-#` emojis to this list or dealing with them with a regex and ignoring the skin tone? Or something else?

**Comment by Kikobeats** [comment]
Hello,

The list is auto-generated: 

https://github.com/Kikobeats/emojis-keywords/blob/master/update.js

that calls to 

https://github.com/Kikobeats/emojis-list/blob/master/update.js#L10

so now it depends directly from twemoji classes name.

I suppose we can do that but first we need to determinate what is the standard way out of there (not yet slack)

**Comment by marti4ka** [comment]
Thanks for the fast response @Kikobeats.
Ok, for now I will just ignore the skin tones and hope that slack starts using twemoji
